### PR TITLE
Write restart files and update input file.

### PR DESCRIPTION
**Pull request by bindi-nagda**
I want to merge this so that I don't have to re-write the restart code when I do a git pull.

### CODE REVIEW

**Comment by abarret** [comment]
Does this input file match what we are currently (or planning on) using in the paper?

**Comment by bindi-nagda** [comment]
Yes, it matches what we are currently using in the paper. I updated it just now so that ETA_S = 0.004 which is what I used for the viscous network simulation. In other words, the solvent is 1000x less viscous than the network. I've also updated the overleaf paper with the correct parameters for the four roll mill experiments.

**Comment by abarret** [comment]
> Yes, it matches what we are currently using in the paper. I updated it just now so that ETA_S = 0.004 which is what I used for the viscous network simulation. In other words, the solvent is 1000x less viscous than the network. I've also updated the overleaf paper with the correct parameters for the four roll mill experiments.

1000? I thought it was 100. Maybe I should read the paper closer... :smile:

**Review by abarret — APPROVED** [review]

**Comment by abarret** [comment]
After we finish the draft, we should make sure we have consistent input files for every simulation that appears in the paper.

**Comment by bindi-nagda** [comment]
I had incorrectly written ETA_S = 0.04 in overleaf. I spent yesterday going through the the input files for Newtonian FRM simulation and can confirm ETA_S = 0.004 for those runs. I am running the viscoelastic simulations for ETA_S = 0.004 though there's is symmetry breaking in Thn and Un towards the end of the run so I'm re-running them. I've reduced the $\Delta t$ and increased rtol and I'll check the results tomorrow.

**Pull request merged**
